config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  # ↑の解説。大事！！get '/' => 'home#top'
  get 'home/about' => 'home#about'
  resources :books
  # get 'books/:id' => 'books#show'
  # get 'books/new' => 'books#new'
  # get 'books/:id/edit' => 'books#edit'
  # put 'books/:id' => 'books#update'
  # get 'books/' =>'books#index'
  # post 'books/' => 'books#create'
  # delete 'books/:id' => 'books#delete'
  devise_for :users
  resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  attachment :profile_image

  has_many :books, dependent: :destroy

  validates :name, presence: true, length: { minimum: 2,maximum: 20}
  validates :introduction, length: { maximum: 50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
  protected


  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:name])
  end

  def after_sign_up_path_for(resource)
     	flash[:notice] = "Signed in successfully."
      users_path(resource.id)
  end

  def after_sign_in_path_for(resource)
     	flash[:notice] = "Welcome!! You loged in successfully!!"
     	user_path(resource.id)
  end

  def after_sign_out_path_for(resource)
  	flash[:notice] = "Signed out successfully."
  	root_path
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def index
    @books = Book.all
    @book = Book.new
    @profile_image = current_user.profile_image
  end

  def create
   @book = Book.new(book_params)
   #↓↓user_idを今ログインしているユーザーのidに設定する
   @book.user_id = current_user.id
     if @book.save
        flash[:notice] = "You have creatad book successfully."
        redirect_to book_path(@book)
     else
        @books = Book.all
        render :index
     end
  end

  def edit
     @book = Book.find(params[:id])
  end

  def show
    @books = Book.all
    @newbook = Book.new
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
       render :edit
    end
  end

  def destroy
     @book = Book.find(params[:id])
       if @book.destroy
          redirect_to books_path
       else
        @books = Book.all
        render :index
       end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book = Book.find(params[:id])
     if @book.user.id != current_user.id
        redirect_to books_path
     end
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
end

def new
end

def create
end

def index
end

def show
  @post_image = PostImage.find(params[:id])
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

before_action :authenticate_user!
before_action :correct_user, only: [:edit, :update]

def index
  @book = Book.new
  @books = Book.all
  @users = User.all
end

def show
  @book = Book.new
  @user = User.find(params[:id])
  @books = @user.books
end

def edit
  @user = User.find(params[:id])
end
# ↓イメージ画像投稿のためにcreateアクション足した
def create
  @profile_image = profile_image.new(profile_image_params)
  @profile_image.user_id = current_user.id
    if @profile_image.save
       redirect_to user_path(@user.id)
    end
  @book = Book.new(book_path)
    if @book.save
       redirect_to book_path(@book.id)
    else
       render :index
    end
end

def update
  @user = User.find(params[:id])
  if @user.update(user_params)
    flash[:notice] = "You have updated user successfully."
    redirect_to user_path(@user.id)
  else
    render :edit
  end
end

private
 def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
 end

 def book_params
    params.require(:book).permit(:title, :body)
 end

 def correct_user
  @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(current_user)
    end
 end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/views/books/_list.html.erb
<div class="container">
  <%= flash[:notice] %>

   <div class="row">
      <div class="col-xs-3">

        <h2>User info</h2>
          <%= attachment_image_tag user, :profile_image, size:"60x60", format: 'jpeg', fallback: "no_image.jpg" %>
            <table class="table">
              <tbody>
                <tr></tr>
                <tr>
                  <th>name</th>
                  <th><%= user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= user.introduction %></th>
                </tr>
              </tbody>
             </table>

            <%= link_to '', edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_id" %>
            <br>

        <h2>New book</h2>
          <%= form_for(book) do |f| %>
            <% if book.errors.any? %>
              <div class="error_message">
                  <h2><strong><%= book.errors.count %>errors prohibited this obj from being saved:</strong></h2>
                  <ul>
                  <% book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
            <% end %>

             <div class="field row">
               <h4>Title</h4>
               <%= f.text_field :title, class: "col-xs-12" %>
             </div>
             <div class="field row">
               <h4>Opinion</h4>
               <%= f.text_area :body, class: "col-xs-12" %>
             </div>
             <div class="actions row">
               <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
             </div>
           <% end %>
      </div>

app/views/books/edit.html.erb
<div class="body">
	<div class="container">
			<div class="row">
				<div class="col-md-6 col-md-offset-3">

						<h1>Editing Book</h1>
						  <%= form_for(@book) do |f| %>
						    <% if @book.errors.any? %>
						      <div class="error_message">
						      	 	<h2><strong><%= @book.errors.count %>errors prohibited this obj from being saved:</strong></h2>
						      	  <ul>
						      		<% @book.errors.full_messages.each do |message| %>
       									<li><%= message %></li>
      								<% end %>
      							  </ul>
      						  </div>
      						<% end %>

							<div class="field row">
							　<h4>Title</h4>
					          <%= f.text_field :title ,class: "col-xs-12" %>
					        </div>

                            <div class="field row">
					          <h4>Opinion</h4>
					          <%= f.text_area :body ,class: "col-xs-12" %>
					        </div>

					        <div class="action row">
					           <input type="submit" name="commit" value="Update Book" class="btn btn-primary col-xs-12" data-disable-with="Update Book">
					        </div>
						  <% end %>
                             <br>
				             <p><%= link_to "Show",book_path(@book) %> | <%= link_to "Back",books_path %></p>
			    </div>
	        </div>
    </div>
</div>

app/views/books/index.html.erb
<%= render 'books/list', book: @book, user: current_user %>
     <div class ="col-xs-9">
      <h2>Books</h2>
       <table class="table table-hover table-inverse">
       	<thead>
       		<tr>
       			<th></th>
       			<th>Title</th>
       			<th>Opinion</th>
       		</tr>
       	</thead>

        <tbody>
          <% @books.each do |book| %>
            <tr>
         			<td><%= link_to user_path(book.user) do %>
                <%= attachment_image_tag book.user, :profile_image, size:"60x60", format: 'jpeg',fallback: "no_image.jpg" %>
                <% end %>
                </td>
         			<td><%= link_to book.title, book_path(book.id) %></td>
         			<td><%= book.body %></td>
            </tr>
          <% end %>
       	</tbody>
       </table>
     </div>
    </div>
  </div>

app/views/books/show.html.erb
<%= render 'books/list', book: @newbook, user:@book.user %>
      <div class="col-xs-9">
          <h2>Book detail</h2>
            <table class="table table-hover table-inverse">
              <tbody>
                  <tr>
                    <td><%= attachment_image_tag @book.user, :profile_image, size:"60x60", format: 'jpeg', fallback: "no_image.jpg", size:"40x40" %>
                      <br>
                    <%= link_to @book.user.name, user_path(@book.user) %>
                    </td>
                    <td>
                      <%= link_to book_path do %>
                      <%= @book.title %>
                      <% end %>
                    </td>
                    <td><%= @book.body %></td>
                    <td>
                      <% if @book.user == current_user %>
                        <td><%= link_to"Edit", edit_book_path(@book), class: "btn-sm btn-success" %></td>
                        <td><%= link_to"Destroy", book_path(@book),  method: :delete, class: "btn-sm btn-danger", "data-confirm" => "本当に削除しますか？" %></td>
                      <% end %>
                    </td>
                  </tr>
              </tbody>
            </table>
      </div>

  </div>
</div>

app/views/home/about.html.erb
<div class="body">
  <div class="container">
  	<h1>Welcome to
		<span class="glyphicon glyphicon-book"></span>
		<strong>Bookers!</strong>
  	</h1>
  </div>
</div>

app/views/home/top.html.erb
  <html>
    <head>
       <link rel="stylesheet" media="all" href="/assets/application-945628f9f95377705c9108ec9a9704e6f6ffa0767c02e34400d75b5be64fc1b7.css" data-turbolinks-track="reload">
       <script src="/assets/application-11e027fe501efa6924bd87aa8f6ef7436fd1539022b412029c4a223dec9664f8.js" data-turbolinks-track="reload"></script>
       <meta name="csrf-param" content="authenticity_token">
       <meta name="csrf-token" content="ZrK2x/Y3ILbby1ZudF2Gs3ABL/UmQjCFnFXSnRAshX6ENbwErf7dL8v9JFGNQdUwh9aDN7L54m84pPjqoU2HtA==">
    </head>

    <body>
       <div class="container">
        <%= flash[:notice] %>
            <div class="row">
              <div class="top-message col-md-offset-3 col-md-6">
                 <h1>welcome to <span class="glyphicon glyphicon-book"><strong>Bookers</strong>  !!</span></h1>
                    <p>In  <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>, </p>
                    <p>you can share and exchange  your opinions , inpressions , and emotions</p>
                    <p> about various books!</p>

                  <div class="btn-wrapper">
                    <div class="row">
                       <p><a class="btn btn-info col-xs-10 col-xs-offset-1 sign_in" href="/users/sign_in">Log in</a></p>
                    </div>
                      <div class="row">
                        <p><a class="btn btn-success col-xs-10 col-xs-offset-1 sign_up" href="/users/sign_up">Sign Up</a></p>
                      </div>
                  </div>
              </div>
            </div>
        </div>
    </body>
  </html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="application.scss">
      <title>Bookers2</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <nav class="nav navbar-nav navbar-left">
          <span class="bookers">Bookers</span>
        </nav>

        <nav>
         <% if user_signed_in? %>
            <ul class="nav navbar-nav navbar-right">
               <li>
                  <%= link_to user_path(current_user.id) do %>
                    <p class="glyphicon glyphicon-home home"> Home</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to users_path do %>
                    <p class="glyphicon glyphicon-link about"> Users</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to books_path do %>
                    <p class="glyphicon glyphicon-book books"> Books</p>
                  <% end %>
                </li>
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                     <p class="glyphicon glyphicon-log-out logout"> logout</p>
                  <% end %>
                 </li>
            </ul>
          <% else %>

          <ul class="nav navbar-nav navbar-right">
            <li>
              <%= link_to root_path do %>
                <p class="glyphicon glyphicon-home home"> Home</p>
              <% end %>
            </li>
            <li>
              <%= link_to home_about_path do %>
                <p class="glyphicon glyphicon-link about"> About</p>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_registration_path do %>
                <p class="glyphicon glyphicon-book books"> sign up</p>
              <% end %>
            </li>
            <li>
              <%= link_to new_user_session_path do %>
                <p class="glyphicon glyphicon-log-out logout"> login</p>
              <% end %>
            </li>
          </ul>
        <% end %>

     </nav>
    </div>
   </header>

<%= yield %>
<footer>
   <div class="container"></div>
   <div class="row"></div>
   <div class="col-xs-3 col-xs-offset-9">
     <p>CopyRight Infratop.inc</p>
   </div>
</footer>


  </body>
</html>

app/views/users/_list.html.erb
<div class="container">
  <%= flash[:notice] %>

   <div class="row">
      <div class="col-xs-3">

        <h2>User info</h2>
          <%= attachment_image_tag user, :profile_image, size:"60x60", format: 'jpeg', fallback: "no_image.jpg" %>
            <table class="table">
              <tbody>
                <tr></tr>
                <tr>
                  <th>name</th>
                  <th><%= user.name %></th>
                </tr>
                <tr>
                  <th>introduction</th>
                  <th><%= user.introduction %></th>
                </tr>
              </tbody>
             </table>

            <%= link_to '', edit_user_path(current_user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_id" %>
            <br>

        <h2>New book</h2>
          <%= form_for(book) do |f| %>
            <% if book.errors.any? %>
              <div class="error_message">
                  <h2><strong><%= book.errors.count %>errors prohibited this obj from being saved:</strong></h2>
                  <ul>
                  <% book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
            <% end %>

             <div class="field row">
               <h4>Title</h4>
               <%= f.text_field :title, class: "col-xs-12" %>
             </div>
             <div class="field row">
               <h4>Opinion</h4>
               <%= f.text_area :body, class: "col-xs-12" %>
             </div>
             <div class="actions row">
               <%= f.submit 'Create Book', class: "btn btn-primary col-xs-12" %>
             </div>
           <% end %>
      </div>

app/views/users/edit.html.erb
<div class="container">
	<h2>User info</h2>
	 <%= form_for(@user) do |f| %>
       <% if @user.errors.any? %>
	      <div class="error_message">
	          <h2><strong><%= @user.errors.count %>errors prohibited this obj from being saved:</strong></h2>
	          <ul>
	           <% @user.errors.full_messages.each do |message| %>
	            <li><%= message %></li>
	           <% end %>
	          </ul>
	      </div>
	   <% end %>

		<div class="field">
			<label for="user_name">Name</label>
			<%= f.text_field :name %>
		</div>

		<div class="field">
			<label for="user_profile_image">Image</label>
			<%= f.attachment_field :profile_image %>
		</div>

		<div class="field">
			<label for="user_introduction">Introduction</label>
			<%= f.text_area :introduction %>
	    </div>

   	<p><%= f.submit "Update User" %></p>
	<% end %>
</div>

app/views/users/index.html.erb
<%= render 'users/list', book: @book, user: current_user %>

<div class="col-xs-9">
	<h2>Users</h2>
    <table class="table table-hover table-inverse">
	 	 <thead>
	 		　<tr>
	 		   <th>image</th>
	  	   <th>name</th>
         <th colspan="3"></th>
	  	  </tr>
	   </thead>

     <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag user, :profile_image, size:"60x60", fallback: "no_image.jpg" %></td>
          <td><%= user.name%></td>
          <td colspan="3"><%= link_to "Show", user_path(user.id) %></td>
        </tr>
     </tbody>
    <% end %>
  </table>
 </div>

</div>

app/views/users/show.html.erb
<%= render 'users/list', book: @book, user: @user %>

      <div class="col-xs-9">
    		<h2>Books</h2>
    		  <table class="table table-hover table-inverse">
    		 	  <thead>
    		 		  <tr>
    		 		   <th></th>
    		 		   <th>Title</th>
    		  	   <th>Opinion</th>
    		  	  </tr>
    		    </thead>

      		   <tbody>
              <% @books.each do |book| %>
               <tr>
                <td><%= attachment_image_tag @user, :profile_image, size:"60x60", format: 'jpeg', fallback: "no_image.jpg" %></td>
                  <td>
                    <%= link_to book_path(book.id) do %>
                    <%= book.title %>
                    <% end %>
                  </td>
        		   	  <td><%= book.body %></td>
      		   	 </tr>
              <% end %>
            </tbody>
          </table>
      </div>

   </div>
 </div>